module Scenic
  self.@configuration: Configuration

  class Configuration
    @database: Adapters::Postgres

    # The Scenic database adapter instance to use when executing SQL.
    #
    # Defaults to an instance of {Adapters::Postgres}
    # @return Scenic adapter
    attr_accessor database: Adapters::Postgres

    def initialize: () -> void
  end

  # @return [Scenic::Configuration] Scenic's current configuration
  def self.configuration: () -> Configuration

  # Set Scenic's configuration
  #
  # @param config [Scenic::Configuration]
  def self.configuration=: (Configuration config) -> Configuration

  # Modify Scenic's current configuration
  #
  # @yieldparam [Scenic::Configuration] config current Scenic config
  # ```
  # Scenic.configure do |config|
  #   config.database = Scenic::Adapters::Postgres.new
  # end
  # ```
  def self.configure: () { (Configuration) -> void } -> Configuration
end
