module Scenic
  self.@configuration: untyped

  class Configuration
    @database: untyped

    # The Scenic database adapter instance to use when executing SQL.
    #
    # Defaults to an instance of {Adapters::Postgres}
    # @return Scenic adapter
    attr_accessor database: untyped

    def initialize: () -> void
  end

  # @return [Scenic::Configuration] Scenic's current configuration
  def self.configuration: () -> untyped

  # Set Scenic's configuration
  #
  # @param config [Scenic::Configuration]
  def self.configuration=: (untyped config) -> untyped

  # Modify Scenic's current configuration
  #
  # @yieldparam [Scenic::Configuration] config current Scenic config
  # ```
  # Scenic.configure do |config|
  #   config.database = Scenic::Adapters::Postgres.new
  # end
  # ```
  def self.configure: () { (untyped) -> untyped } -> untyped
end
